apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    name: web
    app: todoapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - name: web 
        image: registry.example.com:5000/binnyr/todo:v1
        resources:
          requests:
            cpu: 50m 
            memory: 100Mi 
          limits:
            cpu: 100m
            memory: 200Mi 
        env:
          - name: "DBHOST"
            value: "mongodb://todo-mongodb-replicaset-0.todo-mongodb-replicaset,todo-mongodb-replicaset-1.todo-mongodb-replicaset,todo-mongodb-replicaset-2.todo-mongodb-replicaset:27017"
        ports:
        - containerPort: 3000
